name: "Build image, push to custom registry, deploy to Caprover"

on:
  push:
    branches:
      - master


env:
  IMAGE_REPO: registry.minsky.cc/minskylab/totemiq/store-admin
jobs:
  build-push-registry:
    name: Build image and push to custom registry
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: registry.minsky.cc
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_REPO }}
          flavor: |
            latest=true
          tags: |
            type=sha,format=long,prefix=sha-
            type=raw,value=stable,enable=${{ github.ref == 'refs/heads/master' }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          labels: ${{ steps.docker_meta.outputs.labels }}
          tags: ${{ steps.docker_meta.outputs.tags }}



  deploy-caprover-production:
    runs-on: ubuntu-20.04
    needs: [build-push-registry]
    if: github.ref == 'refs/heads/master'
    name: "[Production] Deploy to Caprover"
    steps:
      - name: Deploy to Caprover
        uses: floms/action-caprover@v1
        with:
          host: "${{ secrets.CAPROVER_HOST }}"
          password: "${{ secrets.CAPROVER_PASSWORD }}"
          app: "${{ secrets.CAPROVER_APP_PRODUCTION }}"
          image: "${{ env.IMAGE_REPO }}:sha-${{ github.sha }}"